apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: {{ .Values.image.containerPort }}
      port: 80
