apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_URL: {{ .Values.properties.postgres_url }}
  POSTGRES_PORT: {{ .Values.properties.postgres_port | quote }}
  POSTGRES_DB: {{ .Values.properties.postgres_db | quote }}
  SERVER_PORT: {{ .Values.image.containerPort | quote }}