namespace: trash-talker

image:
  repository: lopesdev/sensors-mock
  pullPolicy: Always
  containerPort: 8091
  tag: ""

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

properties:
  rabbitmq_host: rabbitmq
  rabbitmq_port: 5672
  exchange_name: measurements

