apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ .Values.properties.postgres_host }}
  POSTGRES_PORT: {{ .Values.properties.postgres_port | quote }}
  POSTGRES_DB: {{ .Values.properties.postgres_db | quote }}
