apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  RABBITMQ_HOST: {{ .Values.properties.rabbitmq_host }}
  RABBITMQ_PORT: {{ .Values.properties.rabbitmq_port | quote }}
  EXCHANGE_NAME: {{ .Values.properties.exchange_name | quote }}